My comments
chung3011/fjord-books_app pull request #6
Opened 2022-03-31 03:44 UTC by chung3011

2022-03-31 07:48 UTC, komagata requested changes

2022-03-31 07:48 UTC, komagata commented on app/controllers/reports/comments_controller.rb
> +    comment.save!
ここでエラーだった場合の処理が欲しいです。

2022-03-31 07:48 UTC, komagata commented on db/migrate/20220331033410_create_reports.rb
> +      t.belongs_to :user, null: false, foreign_key: true
foreign_keyをちゃんとはっているのがいいですね👍

2022-03-31 10:23 UTC, chung3011 commented on app/controllers/reports/comments_controller.rb
> +    comment.save!
@komagata さん、コードを更新しました。もう一度チェックをお願いします。

2022-03-31 13:02 UTC, komagata requested changes

2022-03-31 13:02 UTC, komagata commented on app/controllers/books/comments_controller.rb
> +    if @comment.save!
このやり方ですと `save!`の時点でExceptionが発生して処理が止まるかと思います〜

2022-03-31 13:10 UTC, chung3011 commented on app/controllers/books/comments_controller.rb
> +    if @comment.save!
@komagata さん、save!の代わりにsaveを使用しました。

2022-04-04 05:14 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-04-17 04:48 UTC, merged